### ISSUE TITLE
apt-get install fails version 2.3.6

### ISSUE THREAD

**Issue by wonderphil** [treasure-data/omnibus-td-agent#146]
We have puppet that deploys td-agent, as of day its trying to install version 2.3.5-0 and fails to start with the following output:
`
apt-get install td-agent
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed
  td-agent
0 to upgrade, 1 to newly install, 0 to remove and 5 not to upgrade.
Need to get 0 B/55.4 MB of archives.
After this operation, 185 MB of additional disk space will be used.
Selecting previously unselected package td-agent.
(Reading database ... 76424 files and directories currently installed.)
Preparing to unpack .../td-agent_2.3.6-0_amd64.deb ...
Unpacking td-agent (2.3.6-0) ...
Setting up td-agent (2.3.6-0) ...
Conffile /etc/td-agent/td-agent.conf has been modified. Remain untouched.
THANK YOU FOR USING TREASURE DATA’s PACKAGED VERSION OF FLUENTD (TD-AGENT). IF YOU ARE NOT A TREASURE DATA CUSTOMER AND NEED HELP TROUBLESHOOTING OR THE ENTERPRISE VERSION VISIT https://fluentd.treasuredata.com
Starting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'cool.io' (~> 1.4.5) - did find: [cool.io-1.5.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/opt/td-agent/embedded/lib/ruby/gems/2.1.0/', execute `gem env` for more information
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1430:in `each'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1430:in `activate_dependencies'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1412:in `activate'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:300:in `block in activate_bin_path'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:300:in `synchronize'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:300:in `activate_bin_path'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
 * td-agent
invoke-rc.d: initscript td-agent, action "start" failed.
dpkg: error processing package td-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 td-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by repeatedly** [comment]
Which OS do you use?

**Comment by wonderphil** [comment]
Sorry that probably would of helped

using Ubuntu 14.04.5

**Comment by repeatedly** [comment]
Hmm... I re-checked two approaches, new installation and update from td-agent 2.3.5, on my Ubuntu 14.04 but no problem.
So td-agent 2.3.6 itself doesn't have a problem on vanilla setup.
I assume your environment or puppet causes above cool.io conflict.
Does your setup have additional step or something?

**Comment by wonderphil** [comment]
I have the following plugins that i install with the `td-agent-gem install`

fluent-plugin-kinesis
fluent-plugin-grok-parser
fluent-plugin-geoip

wonder if I need to re-do the install for them?

**Comment by wonderphil** [comment]
if I run gem env I get, but thats system ruby isn't it

RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.23
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [x86_64-linux]
  - INSTALLATION DIRECTORY: /var/lib/gems/1.9.1
  - RUBY EXECUTABLE: /usr/bin/ruby1.9.1
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/1.9.1
     - /root/.gem/ruby/1.9.1
     - /usr/share/rubygems-integration/1.9.1
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/

**Comment by wonderphil** [comment]
so as work around I dont the following:

export GEM_HOME="/opt/td-agent/embedded/lib/ruby/gems/2.1.0/"
export GEM_PATH="/opt/td-agent/embedded/lib/ruby/gems/2.1.0/"
/opt/td-agent/embedded/bin/gem install cool.io -v 1.4.5

Agent then starts and if I do a apt-get install td-agent then this works as well.  Not sure where /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/ went but I will just update puppet to do this for now.

**Comment by jurgenhaas** [comment]
I'm having the same problem on Ubuntu 16.04 where I'm managing around 50 hosts. On 5 of them, this problem hit me as well, not so on the other 45. The difference is that on the 5 failing hosts I'm using these three plugins that I'm not using on the other 45:

- fluent-plugin-elasticsearch
- fluent-plugin-elasticsearch-timestamp-check
- fluent-plugin-kvp-filter

The workaround from @wonderphil does help and fixed the problem.

**Comment by repeatedly** [comment]
> I'm having the same problem on Ubuntu 16.04

Same means you got `Could not find 'cool.io' (~> 1.4.5)` messange or got other error message?

**Comment by jurgenhaas** [comment]
Exactly that message.

**Comment by repeatedly** [comment]
Hmm... I installed above 3 gems in td-agent 2.3.5 and I upgraded to td-agent 2.3.6 but fluentd runs withtout problem. 

Does anyone provide reproducible step for this problem?

**Comment by wonderphil** [comment]
I can share our puppet class with you that shows what we are doing?

**Comment by repeatedly** [comment]
I'm not familiar with puppet, so full setup and reproducible step is helpful.

> to_specs': Could not find 'cool.io' (~> 1.4.5) - did find: [cool.io-1.5.1] 

td-agent 2.3.6 bundles cool.io 1.5.1. I assume some gems has `'cool.io' (~> 1.4.5)` dependency in the gemspec, but I'm not sure which one.

**Comment by arthurlm44** [comment]
```
root@staging:/home/provision# export GEM_HOME='/opt/td-agent/embedded/lib/ruby/gems/2.1.0/'; export GEM_PATH='/opt/td-agent/embedded/lib/ruby/gems/2.1.0/'; /usr/sbin/td-agent-gem install fluent-plugin-systemd --version='0.0.8'
/usr/sbin/td-agent-gem: 4: /usr/sbin/td-agent-gem: /opt/td-agent/embedded/bin/fluent-gem: not found
```

Is this related? 
Or is there another issue that I can take a look at to resolve this?

**Comment by repeatedly** [comment]
> Is this related?

https://rubygems.org/gems/fluent-plugin-systemd/versions/0.0.8

I checked fluent-plugin-systemd v0.0.8 but it doesn't have 'cool.io' (~> 1.4.5) dependency, so mabye, the problem is other place.
