### ISSUE TITLE
gcc.exe: error: Files/Git/opt/td-agent/embedded/include: No such file or directory

### ISSUE THREAD

**Issue by jaswinder-trantor** [treasure-data/omnibus-td-agent#147]
I am using latest version 2.3.6 and command used for build is `bundle exec ruby bin/omnibus build td-agent3 -o windows_arch:x64`

terminal logs:

`    $ BINARY_PATH=/bin CFLAGS=-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 CPPFLAGS=-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 CXXFLAGS=-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 DESTDIR=/opt/td-agent/embedded INCLUDE_PATH=/include LDFLAGS=-L/opt/td-agent/embedded/lib -m64 -fno-lto LD_RUN_PATH=/opt/td-agent/embedded/lib LIBRARY_PATH=/lib OMNIBUS_INSTALL_DIR=/opt/td-agent PATH=/opt/td-agent/bin;/opt/td-agent/embedded/bin;C:/Ruby23-x64/lib/ruby/gems/2.3.0/bin;C:\Users\mohammad.aarif\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Ruby23-x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\WiX Toolset v3.10\bin;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files\Git\cmd;C:\DevKit\bin;C:\DevKit\mingw\bin;C:\msys64\usr\bin;C:\DevKit;C:\Users\mohammad.aarif\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl PKG_CONFIG_PATH=/opt/td-agent/embedded/lib/pkgconfig bash -c 'make -fwin32/Makefile.gcc SHARED_MODE=1 CFLAGS="-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 -Wall" ASFLAGS="-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 -Wall" LDFLAGS="-L/opt/td-agent/embedded/lib -m64 -fno-lto"'

Output:

    gcc -IC:/Program Files/Git/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 -Wall -c -o adler32.o adler32.c

Error:

    gcc.exe: error: Files/Git/opt/td-agent/embedded/include: No such file or directory
make: *** [adler32.o] Error 1

C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/util.rb:140:in `rescue in shellout!'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/util.rb:136:in `shellout!'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:845:in `shellout!'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:85:in `block in command'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:1034:in `instance_eval'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:1034:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:863:in `block (3 levels) in execute'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:885:in `with_retries'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:862:in `block (2 levels) in execute'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/instrumentation.rb:23:in `measure'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:861:in `block in execute'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:935:in `with_clean_env'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:860:in `execute'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:752:in `block (2 levels) in build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:751:in `each'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:751:in `block in build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/instrumentation.rb:23:in `measure'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/builder.rb:750:in `build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/software.rb:1209:in `execute_build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/software.rb:1092:in `build_me'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/project.rb:1077:in `block (2 levels) in build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/project.rb:1076:in `each'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/project.rb:1076:in `block in build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/licensing.rb:62:in `block in create_incrementally'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/licensing.rb:57:in `tap'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/licensing.rb:57:in `create_incrementally'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/project.rb:1075:in `build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/cli.rb:89:in `build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/cli/base.rb:33:in `dispatch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/lib/omnibus/cli.rb:42:in `execute!'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/omnibus-52393d7cab44/bin/omnibus:16:in `<top (required)>'
  bin/omnibus:17:in `load'
`

**Comment by repeatedly** [comment]
td-agent itself doesn't fit for td-agent build.
So I'm not sure what is the wrong.

**Comment by jaswinder-trantor** [comment]
I am able to resolve the above issue but getting a different error : 
`The following shell command exited with status 1:

    $ CFLAGS=-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 CPPFLAGS=-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 CXXFLAGS=-I/opt/td-agent/embedded/include -m64 -O3 -march=x86-64 LDFLAGS=-L/opt/td-agent/embedded/lib -m64 -fno-lto LD_RUN_PATH=/opt/td-agent/embedded/lib OMNIBUS_INSTALL_DIR=/opt/td-agent PATH=/opt/td-agent/bin;/opt/td-agent/embedded/bin;c:/Ruby23-x64/lib/ruby/gems/2.3.0/bin;.;C:\DevKit\local\bin;C:\DevKit\mingw\bin;C:\DevKit\bin;c:\Ruby23-x64\bin;c:\Windows\system32;c:\Windows;c:\Windows\System32\Wbem;c:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Skype\Phone\;c:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;c:\Program Files (x86)\WiX Toolset v3.10\bin;c:\Program Files (x86)\Windows Kits\10\bin\x64;c:\Program Files\Git\cmd;c:\msys64\usr\bin;C:\DevKit;c:\Users\mohammad.aarif\AppData\Local\Microsoft\WindowsApps PKG_CONFIG_PATH=/opt/td-agent/embedded/lib/pkgconfig \opt\td-agent\embedded\bin\rake build

Output:

    (nothing)

Error:

    rake aborted!
LoadError: cannot load such file -- bundler/gem_tasks
C:/omnibus-ruby/src/fluentd/fluentd/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)`
