### ISSUE TITLE
misleading error message when wrong privileges on config files

### ISSUE THREAD

**Issue by tmeinlschmidt** [treasure-data/omnibus-td-agent#181]
````
# td-agent --version
td-agent 1.2.4
````

````
# service td-agent restart
Restarting td-agent: ls -l/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:163:in `read': include error conf.d/*.conf (Fluent::ConfigParseError)
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:163:in `block in eval_include'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:160:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:160:in `eval_include'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:145:in `parse_include'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:104:in `parse_element'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:43:in `parse!'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config/v1_parser.rb:33:in `parse'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/config.rb:39:in `parse'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:766:in `read_config'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:477:in `run_supervisor'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.4/bin/fluentd:8:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
````

and it all was caused by wrongly set user:group on one of the configuration file from `/etc/td-agent/conf`

### Suggested solution
Error message should be correct - 'access denied'

**Comment by tmeinlschmidt** [comment]
thanks
