### ISSUE TITLE
cloudwatch_logs plugin fail

### ISSUE THREAD

**Issue by talset** [treasure-data/omnibus-td-agent#184]
Hi,

Im using the 3.2.0 package and see 1/2 days the new install doest work with the `cloudwatch_logs` plugin

Here an example of usage :

```
<match cycloid.system-mail>
@type copy
  <store>
  @type cloudwatch_logs
  @log_level error
  region eu-west-1
  log_group_name prod
  log_stream_name system-mail
  auto_create_stream true
  retention_in_days 180
  </store>
</match>
```

It fail to start with

```
Sep 06 17:14:33 ip-172-31-20-102 systemd[1]: td-agent.service: Start request repeated too quickly.
Sep 06 17:14:33 ip-172-31-20-102 systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
-- Subject: Unit td-agent.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
lines 4590-4642/4654 100%
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-cloudwatchlogs-1.6.0/lib/aws-sdk-cloudwatchlogs.rb:13:in `require_relative'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-cloudwatchlogs-1.6.0/lib/aws-sdk-cloudwatchlogs.rb:13:in `<top (required)>'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.6.1/lib/fluent/plugin/out_cloudwatch_logs.rb:58:in `initialize'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:149:in `new'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:149:in `new_impl'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:104:in `new_output'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/multi_output.rb:72:in `block in configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/multi_output.rb:63:in `each'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/multi_output.rb:63:in `configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/out_copy.rb:36:in `configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:164:in `configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:130:in `add_match'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:72:in `block in configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `each'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:112:in `configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:131:in `configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:96:in `run_configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:795:in `run_configure'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:579:in `dry_run'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:597:in `supervise'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:502:in `run_supervisor'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/bin/fluentd:8:in `<top (required)>'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
Sep 06 17:14:32 ip-172-31-20-102 fluentd[23798]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
Sep 06 17:14:32 ip-172-31-20-102 systemd[1]: td-agent.service: Control process exited, code=exited status=1
Sep 06 17:14:32 ip-172-31-20-102 systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
```

Here are the gem installed : 

```
/opt/td-agent/embedded/bin/gem list | grep sdk-c
aws-sdk-cloudwatchlogs (1.6.0)
aws-sdk-core (3.21.2)
```

I "found" 2 possible fix :

  * Upgrade the aws-sdk-core to 3.26.0
```
/opt/td-agent/embedded/bin/gem install aws-sdk-core -v3.26.0
```

or

  * Downgrade aws-sdk-cloudwatchlogs to 1.5.0

```
/opt/td-agent/embedded/bin/gem install aws-sdk-cloudwatchlogs -v1.5.0
/opt/td-agent/embedded/bin/gem uninstall aws-sdk-cloudwatchlogs  -v 1.6.0
```

WDYT ?

**Comment by talset** [comment]
Well it seems that aws-sdk-cloudwatchlogs 1.7.0 is out and used by default.
It works with it.
