### ISSUE TITLE
td-agent fails when starting it up due to missing 'ripper' gem

### ISSUE THREAD

**Issue by teamhanded** [treasure-data/omnibus-td-agent#242]
I'm using `ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux-gnu]` and when trying to start td-agent  I get the following error:

```
sudo service td-agent start
Starting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ripper (LoadError)
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/config/literal_parser.rb:22:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/config/element.rb:18:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/config.rb:18:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/supervisor.rb:20:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/command/fluentd.rb:19:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/bin/fluentd:8:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
td-agent                                                   [FAILED]
```

Now, ripper will only work in Ruby 1.8, as seen here.

```
sudo td-agent-gem install ripper
ERROR:  Error installing ripper:
	ripper requires Ruby version ~> 1.8.7.
```

I'm running `https://toolbelt.treasuredata.com/sh/install-amazon1-td-agent3.sh` and it's installing `3.2.0-0.el2017`. I can't understand why is it asking for such an old dependency, and I don't think it's wise to install an old Ruby version just to support a single Ruby gem.

I'll appreciate any insights into this.

**Comment by teamhanded** [comment]
Moreover... the RPM I get from the official source

```
$ cat /etc/yum.repos.d/td.repo
[treasuredata]
name=TreasureData
baseurl=http://packages.treasuredata.com/3/amazon/1/$releasever/$basearch
gpgcheck=1
gpgkey=https://packages.treasuredata.com/GPG-KEY-td-agent
```

installs td-agent `v1.10.0 - 2020/03/24`, and in `/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/config/literal_parser.rb`, which comes bundled with td-agent, the following lines invoke and use `ripper` functions:

```
$ grep -iR "ripper" .
./lib/fluent/config/literal_parser.rb:require 'ripper'
./lib/fluent/config/literal_parser.rb:          unless Ripper.sexp(src[0..seek] + '"').nil? # eager parsing until valid expression
```

I don't see any mention of `ripper` in this GitHub repository, save from https://github.com/treasure-data/omnibus-td-agent/commit/ee0db0930d3dbd5bf5b1683dd366e9d2fa041014 - which I understand since it makes sense not to version the bundled gems. However, I'm unsure where the bundling is being done, and why does it require the `ripper` gem which is outdated.

**Comment by teamhanded** [comment]
@repeatedly any insights? Thank you very much.

**Comment by repeatedly** [comment]
> why does it require the ripper gem which is outdated.

No. ruby bundled ripper since ruby 1.9. This is why ripper gem has an installation failure.

If you want to avoid this problem, update your older amazon linux 1 to latest amazon linux 1 or amazon linux 2 is better.
