### ISSUE TITLE
Latest td-agent will not start on centos 8

### ISSUE THREAD

**Issue by neb14** [treasure-data/omnibus-td-agent#253]
Below is the error I am seeing.

```May 07 19:38:43 conduit-console-00 fluentd[18670]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:88: warning: already initialized constant ROTATE_AGE
May 07 19:38:43 conduit-console-00 fluentd[18670]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:88: warning: previous definition of ROTATE_AGE was here
May 07 19:38:43 conduit-console-00 fluentd[18670]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'dig_rb' (>= 0) among 100 total gem(s) (Gem::MissingSpecError)
May 07 19:38:43 conduit-console-00 fluentd[18670]: Checked in 'GEM_PATH=/opt/td-agent/embedded/lib/ruby/gems/2.4.0/', execute `gem env` for more information
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1430:in `each'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1430:in `activate_dependencies'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1412:in `activate'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-geoip-0.8.2/lib/fluent/plugin/filter_geoip.rb:1:in `<top (required)>'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:102:in `block in search'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:99:in `each'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:99:in `search'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/registry.rb:44:in `lookup'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin.rb:155:in `new_impl'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/plugin.rb:113:in `new_filter'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:152:in `add_filter'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:72:in `block in configure'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `each'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/agent.rb:64:in `configure'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/root_agent.rb:146:in `configure'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/engine.rb:105:in `configure'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/engine.rb:80:in `run_configure'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:551:in `run_supervisor'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
May 07 19:38:43 conduit-console-00 fluentd[18670]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
May 07 19:38:43 conduit-console-00 systemd[1]: td-agent.service: Control process exited, code=exited status=1
May 07 19:38:43 conduit-console-00 systemd[1]: td-agent.service: Failed with result 'exit-code'.
```

**Comment by neb14** [comment]
```
[kenna_us_prod_aws root@conduit-console-00 gems]$ rpm -qa | grep td-agent
td-agent-3.7.1-0.el7.x86_64
[kenna_us_prod_aws root@conduit-console-00 gems]$ uname -a
Linux conduit-console-00 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Fri Jan 3 23:55:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[kenna_us_prod_aws root@conduit-console-00 gems]$ cat /etc/
Display all 237 possibilities? (y or n)
[kenna_us_prod_aws root@conduit-console-00 gems]$ cat /etc/centos-release
CentOS Linux release 8.1.1911 (Core) 
```
