### ISSUE TITLE
rewrite-tag-filter not working with td-agent-3.8.0-0.el8.x86_64.rpm

### ISSUE THREAD

**Issue by akshatsharma4** [treasure-data/omnibus-td-agent#271]
Hi, 
We are using td-agent-3.8.0-0.el8.x86_64.rpm in our flunetd centos8 based docker image. We are able to build the image without any issues, but while running the chart, I see the fluentd pod keeps restarting with following error:

`kubectl logs -f fluentd-7b549b8ff8-zrllm -n namespace

2020-11-02 11:04:00 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-amqp' version '0.14.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.9'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-forest' version '0.3.3'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-genhashvalue' version '1.1'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-grok-parser' version '2.6.2'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.2'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-multiline-parser' version '0.1.1'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-out-http' version '1.3.3'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-postgres' version '0.1.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.8.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-remote_syslog' version '1.0.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.3.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-route' version '1.0.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-s3' version '1.3.2'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.1.2'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-11-02 11:04:01 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.5'
2020-11-02 11:04:01 +0000 [info]: gem 'fluentd' version '1.11.1'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rewrite-tag-filter-2.3.0/lib/fluent/plugin/out_rewrite_tag_filter.rb:38:in ``': No such file or directory - hostname (Errno::ENOENT)
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rewrite-tag-filter-2.3.0/lib/fluent/plugin/out_rewrite_tag_filter.rb:38:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/plugin.rb:173:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/agent.rb:132:in `add_match'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/agent.rb:74:in `block in configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/agent.rb:64:in `each'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/agent.rb:64:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:146:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:105:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:80:in `run_configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:551:in `run_supervisor'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/bin/fluentd:8:in `<top (required)>'
        from /opt/td-agent/embedded/bin/fluentd:23:in `load'
        from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
        from /usr/sbin/td-agent:7:in `load'
        from /usr/sbin/td-agent:7:in `<main>'`

There is no other error in the logs apart from this. Any idea how to get it working?

Note that the VM where I am deploying my fluentd chart is a centos-7 based machine, just the base image used in flunetd docker image is centos-8 based image. Will this cause any compatibility issues?

Thanks

**Comment by akshatsharma4** [comment]
Please find the rewrite-tag-filer's configuration below:

'<filter kubernetes.**>
  @type record_transformer
  enable_ruby true
  <record>
    pod-name ${record["kubernetes"]["pod_name"]}
    namespace ${record["kubernetes"]["namespace_name"]}
    tenant_msgtype ${record["kubernetes"]["namespace_name"]}.${record["type"]}
  </record>
</filter>

# retag based on the container name of the log message
<match kubernetes.**>
  @type rewrite_tag_filter
  <rule>
    key tenant_msgtype
    pattern ^(.+)$
    tag nokia.logging.$1
  </rule>
</match>'

**Comment by akshatsharma4** [comment]
The issue occurred because the centos8 base image did not have hostname package installed by default. started working after the required package was installed in the docker.
