### ISSUE TITLE
permission error on td-agent2

### ISSUE THREAD

**Issue by sonots** [treasure-data/omnibus-td-agent#35]
OS: CentOS 6.2

Installing td-agent2 as

```
$ curl -L http://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh
```

The permission of gems directory becomes like

```
ls -ld /opt/td-agent/embedded/lib/ruby/gems/2.1.0/
drwxrwxr-x 8 root root 4096  3月 24 17:17 2015 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/
```

So, td-agent-gem install fails as followings:

```
$ td-agent-gem install fluent-plugin-bigquery
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/td-agent/embedded/lib/ruby/gems/2.1.0/ directory.
```

I can add `sudo`, but it will install gems as root. Writing /etc/td-agent/td-agent.conf as

```
<match **>
  type bigquery
</match>
```

results in an error as below because `td-agent` user can not read gems

```
Starting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- google/api_client (LoadError)
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
```

because it's permission (and permissions of all files in the gem) is set as 

```
$ ls -l /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client.rb
-rw-r----- 1 root root 27249  3月 24 18:19 2015 api_client.rb
```

Changing owner of directories makes succeed:

```
sudo chown td-agent:td-agent -R  /opt/td-agent/embedded/lib/ruby/gems/2.1.0/
```

**Comment by sonots** [comment]
If the owner and group of /opt/td-agent/embedded/lib/ruby/gems/2.1.0/ are td-agent as default, we can install gems with proper permission by running td-agent-gem command as

```
sudo -u td-agent /usr/sbin/td-agent-gem install fluent-plugin-bigquery
```

**Comment by repeatedly** [comment]
How to solve it?
It seems google api client gem issue.

**Comment by sonots** [comment]
> How to solve it?

As I write above?

**Comment by sonots** [comment]
When we use ruby with rbenv or something as usual, the permissions of this gem do not become an issue. So, I can not tell as this is an **issue** of google api client (I am asking the reason not to assign readable permission to others to google api client, though)

This kinds of permission troubles will be a negative reason not to use td-agent.
cf. https://mobile.twitter.com/kenjiskywalker/status/580280069601435648

**Comment by repeatedly** [comment]
It measn sudo /etc/sbin/td-agent-gem uses '-u td-agent' internally?

**Comment by sonots** [comment]
One way is to write document to run as

    sudo -u td-agent td-agent-gem install xxxx

Another way is changing execution owner in td-agent-gem script internally, but I am not investigating well this way yet.

**Comment by sonots** [comment]
I either way, owner and group of gems directory must be td-agent.

**Comment by repeatedly** [comment]
So the solution is below?

1. Set td-agent owner / group to gem directory. Maybe in post install script?
2. Set '-u td-agent' in this line: https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/usr/sbin/td-agent-gem.erb#L4

**Comment by sonots** [comment]
You mean `fluent-gem` command has `-u` option? (I did not know that). If so, your solution looks good.

**Comment by repeatedly** [comment]
Ah, fluent-gem doesn't have it.

Hmm... for safety, under `/opt/td-agent` files should be `td-agent` permission?

**Comment by sonots** [comment]
I agree > /opt/td-agent should be td-agent permission

**Comment by repeatedly** [comment]
When is the best for changing permissions?
Post script, init script or td-agent-gem?

**Comment by sonots** [comment]
I am not familiar with omnibus-ruby, but permission of /opt/td-agent should be td-agent owner when installing the rpm, so not td-agent-gem.

**Comment by repeatedly** [comment]
Could you try `sudo -u td-agent /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch` ?
I hit compilation error related to permission when changed `/opt/td-agent` permission to `td-agent`.

**Comment by sonots** [comment]
Hmm, I succeeded. I am currently changing only `/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems`. 

```
sudo -u td-agent td-agent-gem install fluent-plugin-elasticsearch
Fetching: patron-0.4.20.gem (100%)
Building native extensions.  This could take a while...
Successfully installed patron-0.4.20
Fetching: elasticsearch-api-1.0.7.gem (100%)
Successfully installed elasticsearch-api-1.0.7
Fetching: elasticsearch-transport-1.0.7.gem (100%)
Successfully installed elasticsearch-transport-1.0.7
Fetching: elasticsearch-1.0.8.gem (100%)
Successfully installed elasticsearch-1.0.8
Fetching: fluent-plugin-elasticsearch-0.7.0.gem (100%)
Successfully installed fluent-plugin-elasticsearch-0.7.0
Parsing documentation for elasticsearch-1.0.8
Installing ri documentation for elasticsearch-1.0.8
Parsing documentation for elasticsearch-api-1.0.7
Installing ri documentation for elasticsearch-api-1.0.7
Parsing documentation for elasticsearch-transport-1.0.7
Installing ri documentation for elasticsearch-transport-1.0.7
Parsing documentation for fluent-plugin-elasticsearch-0.7.0
Installing ri documentation for fluent-plugin-elasticsearch-0.7.0
Parsing documentation for patron-0.4.20
Installing ri documentation for patron-0.4.20
Done installing documentation for elasticsearch, elasticsearch-api, elasticsearch-transport, fluent-plugin-elasticsearch, patron after 4 seconds
5 gems installed
```

**Comment by sonots** [comment]
I retried with removing gems, `sudo chown -R td-agent.td-agent /opt/td-agent/`, then install. Success.

**Comment by repeatedly** [comment]
Hmm... which user executes above command?
My test account id is here:

```
y% id
uid=500(repeatedly) gid=500(repeatedly) groups=500(repeatedly) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

**Comment by sonots** [comment]
It's my company dev environment so I can not make it public, but the id is like

```
$ id
uid=500(xxxx) gid=500(xxxx) groups=500(xxxx)
```

The version of sudo would be problem, rather. I have ever seen the behavior of `sudo` is different in different versions. 

```
$ sudo -V
Sudo version 1.7.4p5
```

**Comment by repeatedly** [comment]
My sudo version is here:

```
% sudo -V
Sudo version 1.8.6p3
Sudoers policy plugin version 1.8.6p3
Sudoers file grammar version 42
Sudoers I/O plugin version 1.8.6p3
```

Could you update sudo on your test environment?

**Comment by sonots** [comment]
Updated, but still succeeded. Hmm.

```
$ sudo -V
Sudo version 1.8.6p3
Sudoers policy plugin version 1.8.6p3
Sudoers file grammar version 42
Sudoers I/O plugin version 1.8.6p3
```

**Comment by sonots** [comment]
> compilation error related to permission
can you show details?

**Comment by repeatedly** [comment]
```
[... lots of warning ...]
ument for this option
linking shared-object patron/session_ext.so

make "DESTDIR=" install
/usr/bin/install -c -m 0755 session_ext.so ./.gem.20150324-4065-3w8ap5/patron
installing default session_ext libraries

Permission denied @ dir_chdir - /home/repeatedly

Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/patron-0.4.20 for inspection.
Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/patron-0.4.20/gem_make.out
```

**Comment by sonots** [comment]
In my environment, `sudo -u td-agent` changes `HOME` environment, but it seems yours does not. 

```
$ sudo -u td-agent env | grep HOME
HOME=/var/lib/td-agent
```

Also, the permission of the home directory of execute user was like `drwxr-xr-x`. So, td-agent can chdir in my env.

**Comment by sonots** [comment]
Okay, I got the same error by removing o-rx from my home directory. 

```
$ cd /tmp
$ sudo -u td-agent td-agent-gem install fluent-plugin-elasticsearch
```

made success.

**Comment by repeatedly** [comment]
It seems the problem of google api client.
If someone hit similar problem with regular gems, please re-open this issue.

**Comment by papiveron** [comment]
Hi,

I have an installed td-agent, which doesn't start because of the same and strange error. I set all ownership in all relative files to td-agent:td-agent, but it still doesn't start. This is the error

		Starting td-agent /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/supervisor.rb:53:in `chown': Operation not permitted @ chown_internal - /var/log/td-agent/td-agent.log (Errno::EPERM)
			from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/supervisor.rb:54:in `init'
			from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/supervisor.rb:126:in `start'
			from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
			from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
			from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
			from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/bin/fluentd:6:in `<top (required)>'
			from /opt/td-agent/embedded/bin/fluentd:23:in `load'
			from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
			from /usr/sbin/td-agent:7:in `load'
			from /usr/sbin/td-agent:7:in `<main>'
		 failed!

From ruby file 
		/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/supervisor.rb

I tried to get values passed to the function File.chown(chuid, chgid, @path) at line 53, and I got this 

		/var/log/td-agent/td-agent.log #=> the file name (@path)
                      #=> the user id (chuid)
		4     #=> the groupe id (chgid)

As you can see above, the chuid argument is empty. And the chgid argument is set in the user "admin" in my système, which is not the "td-agent" group. 
However, the init file show the user and group passed to the daemon are "td-agent" and "td-agent"

I'm not the one who installed td-agent. Do someone have ever seen this error? Where can this come from and what should I do?

Thanks a lot for your help.

Regards;

**Comment by papiveron** [comment]
Hi,

I saw the issue. 

The problem was that, in the file "/etc/defautl/td-agent", there was this :+1: 

		 1 # This file is sourced by /bin/sh from /etc/init.d/td-agent                                                                                                                                              
		  2 # Options to pass to td-agent                                                                                                                                                                            
		  3 DAEMON_ARGS="--group adm"                                                                                                                                                                               
		     
I set the DAEMON_ARGS empty, and things got working.

Regards

**Comment by usergoodvery** [comment]
Hi,

I installed on ubuntu xenial using sudo
and I get the:
td-agent[1606]: Starting td-agent: start-stop-daemon: unable to start /opt/td-agent/embedded/bin/ruby (Permission denied)

Originally, the permision were owned by root, reading through this thread, I changed the owner:group to td-agent, and run with sudo as well as sudo -u td-agent, but to no avail...

**Comment by repeatedly** [comment]
This is bigquery plugin issue so you don't need change permission.

**Comment by usergoodvery** [comment]
so what is the remedy?

**Comment by repeatedly** [comment]
Hmm... I didn't receive any report about permission error and there is no error on our test.
Maybe your system needs additional permission change but I'm not sure how to apply it to td-agent.
If you hard to use td-agent, you can use vanilla fluentd gems directly.

**Comment by usergoodvery** [comment]
well this is puzzling.
This is the output of the process. Out of interest, why is it fiddling with mysql?

Hit:1 http://mirrors.linode.com/ubuntu xenial InRelease
Hit:2 http://mirrors.linode.com/ubuntu xenial-updates InRelease
Hit:3 http://mirrors.linode.com/ubuntu xenial-backports InRelease
Hit:4 http://packages.treasuredata.com/2/ubuntu/xenial xenial InRelease
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done
W: http://packages.treasuredata.com/2/ubuntu/xenial/dists/xenial/InRelease: Signature by key C901622B5EC4AF820C38AB861093DB45A12E206F uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  td-agent
0 upgraded, 1 newly installed, 0 to remove and 106 not upgraded.
2 not fully installed or removed.
Need to get 0 B/64.0 MB of archives.
After this operation, 226 MB of additional disk space will be used.
Selecting previously unselected package td-agent.
(Reading database ... 40747 files and directories currently installed.)
Preparing to unpack .../td-agent_2.3.2-0_amd64.deb ...
Unpacking td-agent (2.3.2-0) ...
Setting up mysql-server-5.7 (5.7.13-0ubuntu0.16.04.2) ...
Renaming removed key_buffer and myisam-recover options (if present)
Checking if update is needed.
This installation of MySQL is already upgraded to 5.7.13, use --force if you still need to run mysql_upgrade
dpkg: error processing package mysql-server-5.7 (--configure):
 subprocess installed post-installation script returned error exit status 2
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-5.7; however:
  Package mysql-server-5.7 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Setting up td-agent (2.3.2-0) ...
Conffile /etc/td-agent/td-agent.conf has been modified. Remain untouched.
Job for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details.
invoke-rc.d: initscript td-agent, action "start" failed.
dpkg: error processing package td-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 mysql-server-5.7
 mysql-server
 td-agent
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by repeatedly** [comment]
> why is it fiddling with mysql?

I'm not sure because td-agent doesn't depend mysql.
Here is my installation log.

```
$ curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   563  100   563    0     0    676      0 --:--:-- --:--:-- --:--:--   676
This script requires superuser access to install apt packages.
You will be prompted for your password by sudo.
[sudo] password for repeatedly: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   934  100   934    0     0   4181      0 --:--:-- --:--:-- --:--:--  4188
OK
Get:1 http://packages.treasuredata.com/2/ubuntu/xenial xenial InRelease [1,929 B]
Get:2 http://packages.treasuredata.com/2/ubuntu/xenial xenial/contrib amd64 Packages [398 B]                                            
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease                                                                        
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]                                
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease                 
Get:7 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [129 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [125 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [50.8 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [38.6 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [38.6 kB]
Fetched 574 kB in 2s (261 kB/s)                              
Reading package lists... Done
W: http://packages.treasuredata.com/2/ubuntu/xenial/dists/xenial/InRelease: Signature by key C901622B5EC4AF820C38AB861093DB45A12E206F uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  td-agent
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 64.0 MB of archives.
After this operation, 226 MB of additional disk space will be used.
Get:1 http://packages.treasuredata.com/2/ubuntu/xenial xenial/contrib amd64 td-agent amd64 2.3.2-0 [64.0 MB]
Fetched 64.0 MB in 9s (6,648 kB/s)                                                                                                                           
Selecting previously unselected package td-agent.
(Reading database ... 76037 files and directories currently installed.)
Preparing to unpack .../td-agent_2.3.2-0_amd64.deb ...
Unpacking td-agent (2.3.2-0) ...
Setting up td-agent (2.3.2-0) ...
Adding system user `td-agent' (UID 110) ...
Adding new group `td-agent' (GID 118) ...
Adding new user `td-agent' (UID 110) with group `td-agent' ...
Not creating home directory `/home/td-agent'.
Installing default conffile /etc/td-agent/td-agent.conf ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
```

**Comment by ingoles** [comment]
I am completely new to td-agent. I am getting following error while starting td-agent 

2020-08-24 10:40:12 +0530 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.9'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-prometheus' version '1.8.0'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.3.0'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-s3' version '1.3.2'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-08-24 10:40:12 +0530 [info]: gem 'fluent-plugin-webhdfs' version '1.2.5'
2020-08-24 10:40:12 +0530 [info]: gem 'fluentd' version '1.11.1'
2020-08-24 10:40:12 +0530 [debug]: 'host 127.17.106.30' is tested built-in placeholder(s) but there is no valid placeholder(s). error: Parameter 'host: 127.17.106.30' doesn't have tag placeholder
2020-08-24 10:40:12 +0530 [debug]: Need substitution: true
2020-08-24 10:40:12 +0530 [debug]: 'host_placeholder 127.17.106.30' is tested built-in placeholder(s) but there is no valid placeholder(s). error: Parameter 'host_placeholder: 127.17.106.30' doesn't have tag placeholder
2020-08-24 10:40:12 +0530 [debug]: No fluent logger for internal event
2020-08-24 10:40:12 +0530 [info]: using configuration file: <ROOT>
  <system>
    log_level debug
  </system>
  <source>
    @type tail
    path "/mnt/appln/ncnsintusr/ncns/interface/sol-jms-test/logs/Startup.log"
    pos_file "/mnt/appln/ncnsintusr/ncns/interface/sol-jms-test/logs/Startup.log.pos"
    tag "log"
    <parse>
      @type "none"
      unmatched_lines
    </parse>
  </source>
  <match *log*>
    @type elasticsearch
    host "127.17.106.30"
    port 9200
    scheme http
    ssl_verify false
    ssl_version TLSv1_2
    index_name "fluentd.${tag}"
    type_name "log"
  </match>
</ROOT>
2020-08-24 10:40:12 +0530 [info]: starting fluentd-1.11.1 pid=25631 ruby="2.4.10"
2020-08-24 10:40:12 +0530 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/opt/td-agent/embedded/bin/fluentd", "--log", "/var/log/td-agent/td-agent.log", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2020-08-24 10:40:13 +0530 [info]: adding match pattern="*log*" type="elasticsearch"
2020-08-24 10:40:13 +0530 [debug]: #0 'host 127.17.106.30' is tested built-in placeholder(s) but there is no valid placeholder(s). error: Parameter 'host: 127.17.106.30' doesn't have tag placeholder
2020-08-24 10:40:13 +0530 [debug]: #0 Need substitution: true
2020-08-24 10:40:13 +0530 [debug]: #0 'host_placeholder 127.17.106.30' is tested built-in placeholder(s) but there is no valid placeholder(s). error: Parameter 'host_placeholder: 127.17.106.30' doesn't have tag placeholder
2020-08-24 10:40:13 +0530 [warn]: #0 Detected ES 7.x: `_doc` will be used as the document `_type`.
2020-08-24 10:40:13 +0530 [info]: adding source type="tail"
2020-08-24 10:40:13 +0530 [debug]: #0 No fluent logger for internal event
2020-08-24 10:40:13 +0530 [info]: #0 starting fluentd worker pid=25647 ppid=25642 worker=0
2020-08-24 10:40:13 +0530 [debug]: #0 buffer started instance=70067564453780 stage_size=0 queue_size=0
2020-08-24 10:40:13 +0530 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ dir_s_mkdir - /mnt/appln/ncnsintusr/ncns"
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:227:in `mkdir'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:227:in `fu_mkdir'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:206:in `reverse_each'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:206:in `block in mkdir_p'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:191:in `each'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/plugin/in_tail.rb:214:in `start'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:200:in `block in start'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:188:in `each'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:175:in `each'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:175:in `lifecycle'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/root_agent.rb:199:in `start'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:248:in `start'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/engine.rb:147:in `run'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:603:in `block in run_worker'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:840:in `main_process'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/supervisor.rb:594:in `run_worker'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
20-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.11.1/bin/fluentd:8:in `<top (required)>'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2020-08-24 10:40:13 +0530 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
2020-08-24 10:40:13 +0530 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ dir_s_mkdir - /mnt/appln/ncnsintusr/ncns"
  2020-08-24 10:40:13 +0530 [error]: #0 suppressed same stacktrace
2020-08-24 10:40:13 +0530 [info]: fluent/log.rb:327:info: Worker 0 finished unexpectedly with status 1

td-agent started with root user. owner of the folder /mnt/appln/ncnsintusr/ncns is also root.
Not sure what is the issue. Can someone help to resolve this error. 
I am not able to display log on kibana dashboard because of this issue.
