### ISSUE TITLE
td-agent-gem install fails on fluent-plugin-graphite

### ISSUE THREAD

**Issue by domofactor** [treasure-data/omnibus-td-agent#63]
hey guys,

I'm running into an issue when trying to install the fluent-plugin-graphite gem(0.0.6). FYI, i'm running Ubuntu 14.04.01 and td-agent version 2.3.0 and td-agent-gem version 2.2.1. Any thoughts? Thanks!
```
root@gateway-ubuntu-1404:~# td-agent-gem install fluent-plugin-graphite
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-graphite:
	ERROR: Failed to build gem native extension.

    /opt/td-agent/embedded/bin/ruby extconf.rb
checking for main() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/td-agent/embedded/bin/ruby
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
	--with-cryptolib
	--without-cryptolib
/opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:552:in `try_link0'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:567:in `try_link'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:747:in `try_func'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:978:in `block in have_library'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:923:in `block in checking_for'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:922:in `checking_for'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:973:in `have_library'
	from extconf.rb:8:in `block in check_libs'
	from extconf.rb:8:in `each'
	from extconf.rb:8:in `all?'
	from extconf.rb:8:in `check_libs'
	from extconf.rb:95:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/eventmachine-1.0.9.1/gem_make.out
```

**Comment by yyuu** [comment]
>    /opt/td-agent/embedded/bin/ruby extconf.rb
checking for main() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Read error message. Probably you'd need to install `build-essential` or some other development headers. You should check `mkmf.log` first anyways.

**Comment by domofactor** [comment]
@yyuu well, I feel kinda dumb now. haha totally forgot about trying build-essential. >< 
looks like things are abel to compile properly with that, thanks!
