### ISSUE TITLE
Restarting td-agent for fine work

### ISSUE THREAD

**Issue by ingtarius** [treasure-data/omnibus-td-agent#72]
Hello! 
We have strange issue with td-agents. They working fine in lxc containers (around 100)
Version of td-agent is 2.2.0-1 (we cant update right now, sorry)
When some of lxc restarting - td-agent inside is up, but it does not send data to remote servers (socket and logs sources)
In strace i can find strings like that:
futex(0x7f375dc2d644, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f375dc2d640, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
epoll_wait(87, {}, 64, 998)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 998)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 998)             = 0
epoll_wait(87, {}, 64, 999)             = 0
write(6, "!", 1)                        = 1
futex(0x7f375dc2d610, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f375dc2d640, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f375dc2d644, FUTEX_WAIT_PRIVATE, 69673, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f375dc2d67c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f375dc2d678, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f375dc2d610, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f375dc2d644, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f375dc2d640, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f375dc2d610, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 999)             = 0
write(6, "!", 1)                        = 1
futex(0x7f375dc2d610, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f375dc2d640, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f375dc2d644, FUTEX_WAIT_PRIVATE, 69977, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f375dc2d67c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f375dc2d678, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f375dc2d610, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f375dc2d644, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f375dc2d640, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f375dc2d610, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_wait(87, {}, 64, 998)             = 0
epoll_wait(87, {}, 64, 999)             = 0
epoll_wait(87, {}, 64, 998)             = 0

And i should restarting td-agent few times (1-2-3..10 times) to make it works... Can you help me with this issue?

**Comment by repeatedly** [comment]
I'm not familiar with lxc container.
I want to know this issue happens on non-lxc environment or not.

**Comment by edsiper** [comment]
I am not sure if the strace would help on this scenario, the latest calls just says "I have not received events":
```
epoll_wait(87, {}, 64, 998) = 0
epoll_wait(87, {}, 64, 999) = 0
epoll_wait(87, {}, 64, 998) = 0
```

- can you attach your td-agent log ?
- on which Linux flavor is td-agent running (lxc) ?

**Comment by ingtarius** [comment]
**edsiper**, it is Debian 8.3 Jessie. (host machine and containers, same kernel - 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux )
Here is part of td-agent log
2016-03-28 10:10:45 +0300 [warn]: recovered forwarding server 'collector09:24224' host="collector09" port=24224
2016-03-28 10:10:53 +0300 [error]: error on output thread error="No such file or directory @ sys_fail2 - (/var/log/td-agent/buffer/buffer.all.app.php.integration.b52f169b6e4a81393.log, /var/
log/td-agent/buffer/buffer.all.app.php.integration.q52f169b6e4a81393.log)"
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/plugin/buf_file.rb:68:in `rename'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/plugin/buf_file.rb:68:in `mv'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/plugin/buf_file.rb:183:in `enqueue'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/buffer.rb:276:in `block (2 levels) in push'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/buffer.rb:275:in `block in push'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/buffer.rb:269:in `push'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:278:in `block in enqueue_buffer'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:277:in `each'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:277:in `enqueue_buffer'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:289:in `block in try_flush'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:287:in `try_flush'
  2016-03-28 10:10:53 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:140:in `run'
2016-03-28 10:10:53 +0300 [warn]: detached forwarding server 'collector10:24224' host="collector10" port=24224 phi=18.61422576030188
2016-03-28 10:10:53 +0300 [warn]: recovered forwarding server 'collector04:24224' host="collector04" port=24224
2016-03-28 10:11:03 +0300 [warn]: recovered forwarding server 'collector10:24224' host="collector10" port=24224
2016-03-28 10:11:15 +0300 [warn]: detached forwarding server 'collector09:24224' host="collector09" port=24224 phi=27.114232970124483
2016-03-28 10:11:25 +0300 [warn]: recovered forwarding server 'collector09:24224' host="collector09" port=24224
2016-03-28 10:11:45 +0300 [warn]: detached forwarding server 'collector10:24224' host="collector10" port=24224 phi=16.67454797544008
2016-03-28 10:11:47 +0300 [warn]: detached forwarding server 'collector09:24224' host="collector09" port=24224 phi=31.957110076210828
2016-03-28 10:11:48 +0300 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-28 10:11:49 +0300 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3fd65bcc6318"
  2016-03-28 10:11:48 +0300 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/plugin/out_forward.rb:200:in `write_objects'
  2016-03-28 10:11:48 +0300 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:463:in `write'
  2016-03-28 10:11:48 +0300 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/buffer.rb:325:in `write_chunk'
  2016-03-28 10:11:48 +0300 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/buffer.rb:304:in `pop'
  2016-03-28 10:11:48 +0300 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.14/lib/fluent/output.rb:321:in `try_flush'

**repeatedly**, all apps are in lxc containers, so i cant reproduce this issue without lxc :(

**Comment by repeatedly** [comment]
Could you paste your configuration here?

**Comment by ingtarius** [comment]
Sure. Here is
```
<source>
    type unix
    path /var/run/fluentd.sock
</source>

<source>
    type unix
    path /var/run/fluentd.pixel.sock
</source>

<source>
    type tail_multiline
    tag app.pixel.error
    path /var/log/nginx/pixel_error.log
    pos_file /var/tmp/nginx.error.pixel.pos
    format_firstline /\d{4}/\d{2}/\d+ \d+:\d+:\d+ /
    format /^(?<time>\d{4}/\d{2}/\d+ \d+:\d+:\d+) (?<message>.*)/
</source>

<source>
    type tail_multiline
    tag app.nginx.error_without_hostname
    path /var/log/nginx/nginx.error.log
    pos_file /var/tmp/nginx.error.ru.pos
    format_firstline /\d{4}/\d{2}/\d+ \d+:\d+:\d+ /
    format /^(?<time>\d{4}/\d{2}/\d+ \d+:\d+:\d+) (?<message>.*)/
</source>

<match app.nginx.error_without_hostname>
    type record_reformer
    tag app.nginx.error
    hostname ${hostname}
</match>

<match metric.**>
    type forward
    send_timeout 60s
    heartbeat_interval 2s
    phi_threshold 15

    buffer_queue_limit 512
    buffer_chunk_limit 7m
    flush_interval 1s

    <server>
        host collector01
        port 24224
    </server>
    <server>
        host collector02
        port 24224
        standby
    </server>
    <server>
        host collector03
        port 24224
        standby
    </server>
    <server>
        host collector04
        port 24224
        standby
    </server>
</match>

<match dwh.pa.snippets>
    type mongo_replset
    nodes base1:27017,base2:27017,base3:27017
    name rs01
    database data
    flush_interval 2s
    collection snippets
    buffer_chunk_limit 4m
    buffer_queue_limit 512
    capped
    capped_size 96g
</match>

<match dwh.**>
    type copy
    <store>
        type flowcounter
        count_keys *
        aggregate tag
        output_style joined
        tag fluentd.stats.node.${hostname}
    </store>

    <store>
        type forward
        send_timeout 60s
        heartbeat_interval 2s
        phi_threshold 15

        buffer_type file
        buffer_chunk_limit 4m
        buffer_queue_limit 1024
        buffer_path /var/log/td-agent/buffer/buffer
        flush_interval 1s

        <server>
            host collector05
            port 24224
        </server>
        <server>
            host collector06
            port 24224
        </server>
        <server>
            host collector07
            port 24224
        </server>
        <server>
            host collector08
            port 24224
        </server>
    </store>
</match>

# Send fluent stats to graphite
<match fluentd.stats.node.**>
  type graphite
  host graphite
  port 2003
  tag_for prefix
  name_key_pattern .*
</match>

<match app.firewall.**>
    type forward
    send_timeout 60s
    heartbeat_interval 2s
    phi_threshold 15

    buffer_type file
    buffer_chunk_limit 4m
    buffer_queue_limit 2048
    buffer_path /var/log/td-agent/buffer/buffer.firewall
    flush_interval 1s

    <server>
        host collector04
        port 24224
    </server>
    <server>
        host collector03
        port 24224
    </server>
    <server>
        host collector01
        port 24224
    </server>
    <server>
        host collector02
        port 24224
    </server>
</match>

<match fe.stat>
    type forward
    send_timeout 60s
    heartbeat_interval 2s
    phi_threshold 15

    buffer_queue_limit 512
    buffer_chunk_limit 7m
    flush_interval 1s

    <server>
        host collector09
        port 24224
    </server>
    <server>
        host collector10
        port 24224
    </server>
</match>

<match **>
  type copy
  <store>
    type flowcounter
    count_keys *
    aggregate tag
    output_style joined
    tag fluentd.stats.node.${hostname}
  </store>

  <store>
    type forward
    send_timeout 60s
    heartbeat_interval 2s
    phi_threshold 15

    buffer_type file
    buffer_chunk_limit 4m
    buffer_queue_limit 1024
    buffer_path /var/log/td-agent/buffer/buffer.all
    flush_interval 1s

    <server>
        host collector01
        port 24224
    </server>
    <server>
        host collector02
        port 24224
    </server>
    <server>
        host collector03
        port 24224
    </server>
    <server>
        host collector04
        port 24224
    </server>
  </store>
</match>
```

**Comment by repeatedly** [comment]
You hit the known issue. See buffer_path parameter in this article: http://docs.fluentd.org/articles/buf_file

**Comment by ingtarius** [comment]
OMG!
Thanks a lot!

**Comment by piotrkochan** [comment]
Is there any available resources? I'm facing same issue, td-agent4
