### ISSUE TITLE
CentOS 5 build broken

### ISSUE THREAD

**Issue by cbroglie** [treasure-data/omnibus-td-agent#81]
Getting this error when executing `vagrant up centos-5.11` using the `v2.3.1` tag:
```
==> centos-5.11:  [NetFetcher: makedepend] I | 2016-05-11T07:07:23+00:00 | Downloading from `http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.gz'
==> centos-5.11:
==> centos-5.11:
==> centos-5.11: Progress: |
==> centos-5.11: ===
==> centos-5.11: ==
==> centos-5.11: /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/openssl/ssl.rb:240:in `post_connection_check': hostname "www.x.org" does not match the server certificate (OpenSSL::SSL::SSLError)
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:925:in `connect'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:852:in `start'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:704:in `open'
==> centos-5.11: 	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:34:in `open'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/download_helpers.rb:79:in `download_file!'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/software.rb:843:in `fetch'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:64:in `call'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:62:in `loop'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:61:in `catch'
==> centos-5.11: 	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I can ssh to the VM reproduce the error using curl:
```
[vagrant@localhost ~]$ curl -v -I -L http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.gz
* About to connect() to xorg.freedesktop.org port 80
*   Trying 131.252.210.176... connected
* Connected to xorg.freedesktop.org (131.252.210.176) port 80
> HEAD /releases/individual/util/makedepend-1.0.5.tar.gz HTTP/1.1
> User-Agent: curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
> Host: xorg.freedesktop.org
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Date: Wed, 11 May 2016 07:15:59 GMT
Date: Wed, 11 May 2016 07:15:59 GMT
< Server: Apache/2.4.10 (Debian)
Server: Apache/2.4.10 (Debian)
< Location: https://www.x.org/releases/individual/util/makedepend-1.0.5.tar.gz
Location: https://www.x.org/releases/individual/util/makedepend-1.0.5.tar.gz
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1

* Connection #0 to host xorg.freedesktop.org left intact
* Issue another request to this URL: 'https://www.x.org/releases/individual/util/makedepend-1.0.5.tar.gz'
* About to connect() to www.x.org port 443
*   Trying 131.252.210.176... connected
* Connected to www.x.org (131.252.210.176) port 443
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
SSLv3, TLS handshake, Server hello (2):
SSLv3, TLS handshake, CERT (11):
SSLv3, TLS handshake, Server key exchange (12):
SSLv3, TLS handshake, Server finished (14):
SSLv3, TLS handshake, Client key exchange (16):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSL connection using DHE-RSA-AES128-SHA
* Server certificate:
* 	 subject: /CN=www.freedesktop.org
* 	 start date: 2016-05-06 14:40:00 GMT
* 	 expire date: 2016-08-04 14:40:00 GMT
* SSL: certificate subject name 'www.freedesktop.org' does not match target host name 'www.x.org'
* Closing connection #1
* SSLv3, TLS alert, Client hello (1):
curl: (51) SSL: certificate subject name 'www.freedesktop.org' does not match target host name 'www.x.org'
Closing connection #0
```

I can workaround the `makedepend` software problems by downloading the packages outside the VM and pointing the code to local paths, but this just leads to other SSL errors with other packages later in the build process:
```
/opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:923:in `connect'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:704:in `open'
	from /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/open-uri.rb:34:in `open'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/download_helpers.rb:79:in `download_file!'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/software.rb:843:in `fetch'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:64:in `call'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:62:in `loop'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:61:in `catch'
	from /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-b62510242ece/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
```

The CentOS 5 build was working for me previously, and I suspect the breakages are related to sites dropping SSLv3 support and/or updating updating their certs.

**Comment by repeatedly** [comment]
Yes and this is known issue.
I'm now building td-agent for CentOS 5 manually and I will drop CentOS 5 support soon: https://github.com/treasure-data/omnibus-td-agent/issues/80

**Comment by cbroglie** [comment]
Thanks @repeatedly; to clarify, are you going to be providing fixes for the CentOS 5 build in the short term, or not since you're planning on dropping support?

And are you dropping support due to build issues like these, or b/c new versions will be adding dependencies on packages/features unavailable in CentOS 5?

**Comment by repeatedly** [comment]
> are you going to be providing fixes for the CentOS 5 build in the short term, or not since you're planning on dropping support?

We don't have a plan to fix this build issue because manual build is low cost than fixing this.

> And are you dropping support due to build issues like these

This is one reason and our customers / fluentd users are now moving to newer CentOS versions.
So providing td-agent for CentOS 5 are less important for almost fluentd users.
We have already dropped debian 6 and Ubuntu 10.04 support are same reason.

**Comment by cbroglie** [comment]
Yeah, I understand, I wish we didn't need to continue supporting CentOS 5 ourselves.

Can you share some information about the manual build?

**Comment by repeatedly** [comment]
This is my manual step.

- Launch CentOS 5
- Build latest OpenSSL with shared
- Build Ruby with above OpenSSL
- Install omnibus using above Ruby
- Follow omnibus-td-agent step

If you hit cacert related error, adding 1024bit CA to cacert may resolve the problem: https://github.com/treasure-data/omnibus-td-agent/commit/93e12cbdf70d5c2e8554e470072668c4651e506e#diff-1bc5fe581b71546ca4f2fce94ddcdcc5L71

**Comment by cbroglie** [comment]
Thanks for the tips. I was actually able to get the CentOS 5 build working by leveraging S3 caching, and populating the cache using the CentOS 6 VM. Recommend this approach to anyone else trying to build CentOS 5.
